### ISSUE TITLE
AnyBus : Unidentified Conflicts

### ISSUE THREAD

**Issue by MaraScott** [MaraScott/ComfyUI_MaraScott_Nodes#151]
It seems that the latest ComfyUI [Front-end](https://github.com/Comfy-Org/ComfyUI_frontend) version (starting with 1.3.1) is introducing additional AnyBus issues:

After a workflow reload the assigned pin types (model, clip, vae, latent...) are no longer set
Sometimes AnyBus connections using string type nodes (multi-line etc.) have empty / undefined outputs. The data is not being set or routed correctly. I'm still looking for a reproducible pattern.
I'll try to do some debugging and will open an issue or PR when I find out more.

**Comment by MaraScott** [comment]
@masslevel Arf, please share your workflow.

**Comment by masslevel** [comment]
Sorry for the late reply, @MaraScott . I was a bit busy with other projects.

There seems to be a couple of issues. Especially when sending So AnyBus for me is very much broken in the latest ComfyUI + the latest MaraScott Nodes version. There are JS and python errors. I guess some stuff has changed under the hood in ComfyUI.

I would love for this to work again since it's the best bus node since it also supports KJ's set and get nodes. I tried but I couldn't figure it out yet. Right now it's out of my wheelhouse.

There are 3 distinct problems right now.

1) It doesn't remember the pin types if you reload a workflow
- All pin types are green after a workflow reload
- Connections are still routed through, but there are cases where some pins are empty (ex. text string types)

--

2) Right now you can't connect two AnyBus nodes without getting this JS error:
```js
Uncaught TypeError: node.graph.links.find is not a function
```

### Reproducing
- Latest ComfyUI version
- Create an empty workflow
- Create 2 AnyBus nodes
- Connect both AnyBus nodes
- This leads to the above JS error

### Example GIF with an empty workflow
![marascott-anybus-js-error-20241023](https://github.com/user-attachments/assets/87626f06-ba95-4361-ad53-7a16fe07eb12)

--

3) When connecting string type nodes to AnyBus, the string isn't being forwarded to another Bus. It will be empty. In case of a text encoder you get this message because the string is empty even though it shouldn't be:
```python
AttributeError: 'NoneType' object has no attribute 'replace'
```

If I can help in any other way with testing, creating workflows or more detailed reporting, please let me know anytime.
I will try to some more debugging.

Thank you so much!

**Comment by masslevel** [comment]
```js
Uncaught TypeError: node.graph.links.find is not a function
```

I've to verify this, but I think this might have something to do with `.find()` not getting an array returned by `node.graph.links`.

**Comment by MaraScott** [comment]
Thx @masslevel for suggested fix, https://github.com/MaraScott/ComfyUI_MaraScott_Nodes/pull/172
