### ISSUE TITLE
does not support tiled controlnet when upscale image

### ISSUE THREAD

**Issue by frankyifei** [MaraScott/ComfyUI_MaraScott_Nodes#47]
I will apply controlnet with original image to each tile, and end up with something like this. It does not work even if you set the output size as same size.
![ComfyUI_temp_ypfak_00001_](https://github.com/davask/ComfyUI_MaraScott_Nodes/assets/8104251/a6d4bb5c-5705-4a47-ab9f-c5b13ed08b5c)

**Comment by davask** [comment]
original issue https://github.com/davask/ComfyUI_MaraScott_Nodes/issues/45

**Comment by frankyifei** [comment]
Ok, ultimate sd upscaler  support controlnet and one of the reason to use tile controlnet is to add detail while not change image.

**Comment by davask** [comment]
Thx, I ll check ultimate SD upscaler then :)

**Comment by MaraScott** [comment]
@frankyifei , after debate on fern discord, we come to the point that upscaling comes far down after the control net and using an upscaler/refiner like McBoaty as the goal to refine it while increasing the size (are not) so it won t involved control net.

I will give you @treeshark aka Rob Adams answer on that topic

> I doubt if any tiled upscale would. I could make a flow that worked with control net, you would have to divide up the canny or depth for each tile. So tile one would get the appropriate bit of guidance. I don't see the point though, refining and upscaling is for after you have resolved your image. Control nets and Adapters are best applied at a lower res.

So even if I do want to make McBoaty compatible with whatever comes in, for now - because of a lack of free time - I won t include it.

I hope you will still enjoy what McBoaty can bring to you up to .35 / .45 denoise you should enjoy it perfectly and for sure you need to provide an image without controlNet in it.
